name: BlackDuck Scan
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *" # daily at 03:00
  repository_dispatch:
    types: [master]

env:
  CODEDX_SERVER_PROJECT_ID: 120
  DEP_CHECK_TOOL_VERSION: 6.5.3
  PROJECT_NAME: 'uikit'
  BLACKDUCK_VERSION: 7
  BLACKDUCK_PACKAGES_PARAM: '[{"name":"uikit-core", "paths":[{"path":"/packages/core/dist"}, {"path": "/packages/core/src"}]},{"name":"uikit-lab", "paths":[{"path":"/packages/lab/dist"}, {"path": "/packages/lab/src"}]},{"name":"uikit-icons", "paths":[{"path":"/packages/icons/dist"}, {"path": "/packages/icons/src"}]},{"name":"uikit-themes", "paths":[{"path":"/packages/themes/dist"}, {"path": "/packages/themes/src"}]},{"name":"uikit-code-editor", "paths":[{"path":"/packages/code-editor/dist"}, {"path": "/packages/code-editor/src"}]}]'
  BLACKDUCK_COMPONENT_EXCEPTIONS_PARAM: '@hitachivantara/uikit-react-core @hitachivantara/uikit-react-lab @hitachivantara/uikit-react-icons @hitachivantara/uikit-common-themes @hitachivantara/uikit-react-code-editor'
       

jobs:
  BlackDuckScan:
    name: BlackDuck Scan
    runs-on: [self-hosted, Linux]

    steps:
      - name: Discover current branch
        run: |
          REF=$( echo "${{ github.ref }}" ) # gets the branch or tag ref that triggered the workflow (something like 'refs/heads/branch-name')
          REF=$( echo ${REF##*/} ) # removes the 'refs/heads/' reference
          echo "CURRENT_BRANCH=$REF" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build uikit
        run: |
          npm ci
          npm run bootstrap
          npm run build

      - name: Run Blackduck Scan
        uses: ./.github/blackduck-scan
        with:
          server-url: '${{ secrets.BLACKDUCK_SERVER_URL }}'
          key: '${{ secrets.BLACKDUCK_TOKEN }}'
          version: '${{ env.CURRENT_BRANCH }}'
          packages: '${{ env.BLACKDUCK_PACKAGES_PARAM }}'
          exceptions: '${{ env.BLACKDUCK_COMPONENT_EXCEPTIONS_PARAM }}'
          base-path: '/github/workspace'
